### ISSUE TITLE
Write Pseudo-code for board representation

### ISSUE THREAD

**Issue by abrahimt** [chanson02/KnO3#2]
Now that we have some experience with Rust, let's start by laying out the pseudo-code for the first part of our chess engine (pieces and rules.)

Some ideas for what we'll need:
- Where each piece is
- Whether the game is over or not
- Whose turn it is 
- Legal moves
- Capturing pieces
- En passant square
- Castling Status
- Use of FEN to represent board position
- Whether a square is occupied or not 
- What's occupying a certain square
- Notation converter to bit boards
- Taking an FEN to make a position

**Comment by chanson02** [comment]
For the scope of this issue, I think we can cut it down by removing legal moves, capturing pieces, and the FEN stuff. This issue should only focus on how to _model_ a chess board in a computer memory. No need to worry about performing computation on that memory just yet.

**Comment by abrahimt** [comment]
> For the scope of this issue, I think we can cut it down by removing legal moves, capturing pieces, and the FEN stuff. This issue should only focus on how to _model_ a chess board in a computer memory. No need to worry about performing computation on that memory just yet.

Okay sounds good. I figured we could add the pseudo code for it just so we have an idea of how that will be executed.
